name: Build
on:
  push:
    branches: [build]
jobs:
  build:
    runs-on: [ubuntu-latest]
    continue-on-error: ${{ matrix.supported }}
    strategy:
      matrix:
        variant: [aws-ecs-1]
        arch: [x86_64]
        supported: [true]
        include:
          - variant: aws-dev
            arch: x86_64
            supported: false
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install liblz4-tool
      - run: cargo install --version 0.30.0 cargo-make
      - run: cargo install --version 0.6.6 cargo-deny --no-default-features
      - run: cargo make -e BUILDSYS_VARIANT=${{ matrix.variant }} unit-tests
      - run: cargo make -e BUILDSYS_VARIANT=${{ matrix.variant }} -e BUILDSYS_ARCH=${{ matrix.arch }} -e BUILDSYS_JOBS=12
